### ISSUE TITLE
Write a rosnode that translates the gazebo motion format to profactor format

### ISSUE THREAD

**Issue by JakobThumm** [JakobThumm/human-gazebo#1]
The [motion capture plugin](https://github.com/JakobThumm/human-gazebo/blob/main/src/motion_capture.cc) outputs its measurements in the format provided by the animation files (from CMU).
For concert, we need the format to be in [profactors format](https://github.com/manuelvogel12/sara-shield/blob/main/safety_shield/config/profactor_mocap.yaml).
Write a ROS node that takes in the measurements from the motion capture plugin and outputs measurements in the profactor format. 
If there are no measurements for certain joints, e.g., eyes, duplicate the closest existing measurement, e.g, head.

**Comment by manuelvogel12** [comment]
Merged in #2
